version: "3"

services:
  nextjs-app:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - nestjs-backend
    networks:
      - app-network
    environment:
    - BACKEND_URI=http://moviesmonorepoapp-nestjs-backend-1:8000

  nestjs-backend:
    build: ./back
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge