version: "3"

services:
  nextjs-app:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - nestjs-backend

  nestjs-backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"